FROM gcr.io/google.com/cloudsdktool/cloud-sdk:331.0.0

# Fetch recent go version.
ENV GOLANG_VERSION 1.20.7
ENV GOLANG_DOWNLOAD_URL https://golang.org/dl/go$GOLANG_VERSION.linux-amd64.tar.gz
ENV GOLANG_DOWNLOAD_SHA256 f0a87f1bcae91c4b69f8dc2bc6d7e6bfcd7524fceec130af525058c0c17b1b44

RUN curl -fsSL "$GOLANG_DOWNLOAD_URL" -o golang.tar.gz \
    && echo "$GOLANG_DOWNLOAD_SHA256  golang.tar.gz" | sha256sum -c - \
    && tar -C /usr/local/ -xzf golang.tar.gz \
    && rm golang.tar.gz

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH

# Install binaries needed for builds and testing.
RUN apt-get --allow-releaseinfo-change update
RUN apt-get install -y jq gcc netcat
RUN go install -v github.com/m-lab/gcp-config/cmd/cbif@v1.3.12

ENTRYPOINT ["/go/bin/cbif"]
