#!/bin/sh
# Intended for use with m-lab/git-hooks.
# Clone or use submodule, and link .git/hooks to git-hooks,
#  e.g.
#    mv .git/hooks .git/hooks.orig
#    ln -s ../../git-hooks .git/hooks
#

set -x
set -u
# travis lint -x # Already done by git-hooks/pre-commit

# TODO There are still a LOT of lint warnings, so skip this for now.
# golint ./...
golint ./storage/... ./task/...

# Shadow declarations cause a lot of bugs.  Currently clean.
go tool vet --shadow .

# These are now clean for vet
go vet ./annotation/... ./appengine/... ./fake/... ./metrics/... ./schema/... ./task/... ./web100/...

# These are currently partially clean
go vet -assign -atomic -bool -buildtags -cgocall -copylocks -httpresponse -methods -nilfunc -printf -rangeloops -shift -structtags -tests -unreachable -unsafeptr -unusedresult ./bq/... ./etl/... ./parser/... ./storage/...

# These still have failures in some package
# go vet -composites -lostcancel ./...

