runtime: go111
service: queue-pusher

handlers:
- url: /.*
  script: auto

env_variables:
  # These should be substituted in the travis deployment script.
  RELEASE_TAG: ${TRAVIS_TAG}
  COMMIT_HASH: ${TRAVIS_COMMIT}
