runtime: custom
env: flex
service: etl-parser

# Resource and scaling options. For more background, see:
#   https://cloud.google.com/appengine/docs/flexible/go/configuring-your-app-with-app-yaml

# TODO(dev): adjust CPU and memory based on actual requirements.
resources:
  cpu: 2
  # Instances support between [(cpu * 0.9) - 0.4, (cpu * 6.5) - 0.4]
  # Actual memory available is exposed via GAE_MEMORY_MB environment variable.
  memory_gb: 12

  # TODO - Adjust once we understand requirements.
  disk_size_gb: 10

  # The tmpfs space is allocated from memory_gb.
  volumes:
  # Define a tmpfs disk for NDT snapshot files.
  # Mounted under: /mnt/tmpfs
  - name: tmpfs
    volume_type: tmpfs
    size_gb: 1.0

automatic_scaling:
  # We expect fairly steady load, so a modest minimum will rarely cost us anything.
  min_num_instances: 2
  max_num_instances: 20
  cool_down_period_sec: 300
  # We don't care much about latency, so a high utilization is desireable.
  cpu_utilization:
    target_utilization: 0.95

# Note: add a public port for GCE auto discovery by prometheus.
# TODO(dev): are any values redundant or irrelevant?
network:
  instance_tag: etl-parser
  name: default
  # Forward port 9090 on the GCE instance address to the same port in the
  # container address. Only forward TCP traffic.
  # Note: the default AppEngine container port 8080 cannot be forwarded.
  forwarded_ports:
    - 9090/tcp

health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 10
  unhealthy_threshold: 2
  healthy_threshold: 2

